#===========
# wxWidgets-3.0.1
#===========

#static:
d:
cd d:\Data\wxWidgets-3.0.1_static
Path=d:\MinGW\bin;d:\MinGW\msys\1.0\bin;d:\data\wxWidgets-3.0.1_static\lib;%PATH%
d:\MinGW\msys\1.0\bin\sh.exe configure --with-msw --disable-debug --disable-debug_gdb --disable-shared --enable-stl --enable-std_string --enable-std_iostreams
make clean
make

#dynamic + debug:
d:
cd d:\Data\wxWidgets-3.0.1
Path=d:\MinGW\bin;d:\MinGW\msys\1.0\bin;d:\data\wxWidgets-3.0.1\lib;%PATH%
d:\MinGW\msys\1.0\bin\sh.exe configure --with-msw --enable-stl --enable-std_string --enable-std_iostreams
make clean
make


#-----------------------------
#Otpakujes wxWidgets-2.9.4 u:
#c:\Data\wxWidgets-2.9.4_static
#i onda kucas redom:
#-----------------------------
d:
cd c:\Data\wxWidgets-2.9.4_static

#-----------------------------
#Ovde u cmd-u promenis path tako da zamenis sva pojavljivanja wxWidgetsa
#tako da pokazuju na tvoju novu lokaciju wxWidgets-2.9.4_static
#-----------------------------
Path=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;c:\data\wxWidgets-2.9.4_static\lib;%PATH%

#-----------------------------
#Opalis configure ovako:
#-----------------------------
c:\MinGW\msys\1.0\bin\sh.exe configure --with-msw --disable-debug --disable-debug_gdb --disable-shared --enable-stl --enable-std_string --enable-std_iostreams


#-----------------------------
#Opalis configure ovako za dinamicki build
#-----------------------------
c:\MinGW\msys\1.0\bin\sh.exe configure --with-msw --enable-stl --enable-std_string --enable-std_iostreams --enable-debug
#-----------------------------
#I onda kucas samo make:
#-----------------------------
make


#moja verzija
#stavio u path c:\data\wxWidgets-2.9.4_static\lib;c:\data\MinGW\bin;c:\DATA\MinGW\msys\1.0\bin;c:\data\wxWidgets-2.9.4_static
#verovatno treba jos nesto u path
#otisao u c:\Data\wxWidgets-2.9.4static\
#i opicio
c:\Data\MinGW\msys\1.0\bin\sh.exe configure --with-msw --disable-debug --disable-debug_gdb --disable-shared --enable-stl --enable-std_string --enable-std_iostreams

#time se konfigurisao wxwidgets, sad bi trebalo da se builduje sa make:
c:\Data\MinGW\msys\1.0\bin\make

#posle toga sve buildujes iz NetBeans-a

